### ISSUE TITLE
无法返回回答

### ISSUE THREAD

**Issue by zmcmcc** [circlestarzero/EX-chatGPT#15]
Traceback (most recent call last):
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/zhangmeng/Downloads/EX-chatGPT-main/chatGPTEx/main.py", line 34, in get_bot_response
    res = parse_text(web(q,conv_id=uuid))
  File "/Users/zhangmeng/Downloads/EX-chatGPT-main/chatGPTEx/search.py", line 76, in web
    apir = APIQuery(query,resp=resp)
  File "/Users/zhangmeng/Downloads/EX-chatGPT-main/chatGPTEx/search.py", line 151, in APIQuery
    response =  chatbot.ask(prompt,convo_id='api')
  File "/Users/zhangmeng/Downloads/EX-chatGPT-main/chatGPTEx/optimizeOpenAI.py", line 206, in ask
    full_response: str = "".join(response)
  File "/Users/zhangmeng/Downloads/EX-chatGPT-main/chatGPTEx/optimizeOpenAI.py", line 154, in ask_stream
    response = self.session.post(
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/zhangmeng/opt/anaconda3/lib/python3.9/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

**Comment by circlestarzero** [comment]
SSL error

**Comment by zmcmcc** [comment]
那怎么解决呢。。
