### ISSUE TITLE
proxy issue

### ISSUE THREAD

**Issue by collins7184** [circlestarzero/EX-chatGPT#23]
环境：wsl2 ubantu-22.04 lts 
运行程序时调用proxychains，走socks5通道
Traceback (most recent call last):
  File "/home/collins/.local/lib/python3.10/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/collins/.local/lib/python3.10/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/collins/.local/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/collins/.local/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/collins/.local/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/collins/.local/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/collins/EX-chatGPT/chatGPTEx/main.py", line 55, in get_bot_response
    res = parse_text(detail(q,conv_id=uuid))
  File "/home/collins/EX-chatGPT/chatGPTEx/search.py", line 46, in detail
    call_res0 = search(APIQuery(query),1000)
  File "/home/collins/EX-chatGPT/chatGPTEx/search.py", line 130, in APIQuery
    response =  chatbot.ask(prompt,convo_id='api')
  File "/home/collins/EX-chatGPT/chatGPTEx/optimizeOpenAI.py", line 219, in ask
    full_response: str = "".join(response)
  File "/home/collins/EX-chatGPT/chatGPTEx/optimizeOpenAI.py", line 163, in ask_stream
    API_PROXY = str(config['Proxy']['api_proxy'])
  File "/usr/lib/python3.10/configparser.py", line 964, in __getitem__
    raise KeyError(key)
KeyError: 'Proxy'

来自chatgpt的回答：
这个错误提示是在运行 Python 代码时出现的，它告诉我们程序在解析配置文件时出现了错误，因为没有找到名为 "Proxy" 的关键字。

具体来说，程序中使用了 Python 标准库中的 ConfigParser 模块来读取配置文件，但是在配置文件中没有找到名为 "Proxy" 的关键字。可能的原因是配置文件格式不正确，或者缺少了必要的配置项。

解决此错误的方法包括：

检查程序中使用的配置文件路径是否正确。
检查配置文件中是否有名为 "Proxy" 的关键字，并且确保它的格式正确。
如果程序依赖于外部配置文件，可以尝试重新下载或者更新配置文件。
希望这些提示可以帮助您解决问题。

**Comment by collins7184** [comment]
问题已解决，问题原因：apikey.ini 未及时更新
多谢！(^///^)
