### ISSUE TITLE
无法安装azure-storage

### ISSUE THREAD

**Issue by HeMuling** [circlestarzero/EX-chatGPT#34]
```
(base) he_muling@MacBook-Pro EX-chatGPT % pip install -r requirements.txt
Collecting azure_storage==0.37.0
  Using cached azure-storage-0.37.0.zip (4.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/4z/kspnn2f503550_nfygz4qbr00000gn/T/pip-install-c52stlm7/azure-storage_b80c1df728eb408b8e92646cdd6a0b69/setup.py", line 55, in <module>
          raise RuntimeError(message)
      RuntimeError:
      
      Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
      Please install the service specific packages prefixed by `azure` needed for your application.
      
      The complete list of available packages can be found at:
      https://aka.ms/azsdk/python/all
      
      Here's a non-exhaustive list of common packages:
      
      - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
      - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
      - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
      - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by s1251768942** [comment]
好像是azure-storage被拆分成了很多个模块azure-storage-file-share，azure-storage-blob，azure-storage-file-datalake，azure-storage-queue，azure-storage被移除了。
