### ISSUE TITLE
ModuleNotFoundError: No module named 'graiax'

### ISSUE THREAD

**Issue by luckyhug** [circlestarzero/EX-chatGPT#45]
似乎在requirements里面包没有给全？

**Comment by stormcenter** [comment]
运行时报一样的错误
$ python main.py 
Traceback (most recent call last):
  File "/media/chi/extension/develop/EX-chatGPT/chatGPTEx/main.py", line 8, in <module>
    from graiax.text2img.playwright.plugins.code.highlighter import Highlighter
  File "/home/chi/miniconda3/lib/python3.10/site-packages/graiax/text2img/playwright/__init__.py", line 3, in <module>
    from .renderer import HTMLRenderer, PageOption, ScreenshotOption
  File "/home/chi/miniconda3/lib/python3.10/site-packages/graiax/text2img/playwright/renderer.py", line 8, in <module>
    from graiax.playwright import PlaywrightBrowser
ModuleNotFoundError: No module named 'graiax.playwright'

**Comment by blackwint3r** [comment]
如果安装了graiax-playwright仍然报错， 需要再安装 graiax-text2img-playwright
